@startuml

abstract class AbstractList
abstract AbstractCollection
interface List
interface Collection

List <|-- AbstractList
Collection <|-- AbstractCollection

Collection <|- List
AbstractCollection <|- AbstractList
AbstractList <|-- ArrayList

class ArrayList {
Object[] elementData
size()
}

enum TimeUnit {
DAYS
HOURS
MINUTES
}

@enduml
泛化， Generalization ： <|--
关联， Association ： <--
组合， Composition ： *--
聚合， Aggregation ： o--
实现， Realization ： <|..
依赖， Dependency ： <..